# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alcoholics Anonymous, Savannah
email: webmaster@savannahaa.com
description: > # this means to ignore newlines until "baseurl:"
  ALCOHOLICS ANONYMOUS is a fellowship of men and women who share
  their experience, strength and hope with each other that they may
  solve their common problem and help others to recover from alcoholism.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.savannahaa.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
